# Generated by Django 5.1.7 on 2025-04-10 23:11

from django.db import migrations

def forwards_func(apps,schema_editor):
    Gender = apps.get_model('authentication','Gender')
    Gender.objects.create(name='Masculino',short='M')
    Gender.objects.create(name='Femenino',short='F')
    Gender.objects.create(name='Otro',short='O')

def reverse_func(apps,schema_editor):
    Gender = apps.get_model('authentication','Gender')
    Gender.objects.filter(name='Masculino').delete()
    Gender.objects.filter(name='Femenino').delete()
    Gender.objects.filter(name='Otro').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func,reverse_func)
    ]
