# Generated by Django 5.1.8 on 2025-05-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20250410_2311'),
        ('authorization', '0002_userhasrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='user_has_roles', through='authorization.UserHasRole', to='authorization.role'),
        ),
    ]
