# Generated by Django 5.1.8 on 2025-05-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_roles'),
        ('authorization', '0007_permission_role_description_rolepermission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.ManyToManyField(related_name='user_has_permissions', through='authorization.UserPermission', to='authorization.permission'),
        ),
    ]
