# Generated by Django 5.1.8 on 2025-05-12 00:02

from django.db import migrations

def forwards_func(apps,schema_editor):
    Rol = apps.get_model('authorization','Role')
    Rol.objects.create(name='admin')

def reverse_func(apps,schema_editor):
    Rol = apps.get_model('authorization','Role')
    Rol.objects.filter(name='admin').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_alter_role_name'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
